// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZceANQ97La9Xaix4OwjDKlWQbQ43vo90',
    appId: '1:734184596643:web:33c8fa94bc5c68e9cacb16',
    messagingSenderId: '734184596643',
    projectId: 'flutter-test-a1515',
    authDomain: 'flutter-test-a1515.firebaseapp.com',
    storageBucket: 'flutter-test-a1515.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7tb_RuD26PCHR_8TAs76ALekpDRxs_pw',
    appId: '1:734184596643:android:390a216637044063cacb16',
    messagingSenderId: '734184596643',
    projectId: 'flutter-test-a1515',
    storageBucket: 'flutter-test-a1515.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNetP3hN5oyfNr21UrDklT2u_mQZfYw6k',
    appId: '1:734184596643:ios:a4b7f241978dd1e9cacb16',
    messagingSenderId: '734184596643',
    projectId: 'flutter-test-a1515',
    storageBucket: 'flutter-test-a1515.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNetP3hN5oyfNr21UrDklT2u_mQZfYw6k',
    appId: '1:734184596643:ios:82efff5a7b34d845cacb16',
    messagingSenderId: '734184596643',
    projectId: 'flutter-test-a1515',
    storageBucket: 'flutter-test-a1515.appspot.com',
    iosBundleId: 'com.example.login.RunnerTests',
  );
}
